name: portfolio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^9.0.3
  flutter_svg: ^2.0.7
  flutter_riverpod: ^2.3.6
  url_strategy: ^0.2.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # fonts
    - assets/fonts/gilroy/

  fonts:
    # Gilroy Font
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
        - asset: assets/fonts/gilroy/Gilroy-LightItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-RegularItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Black.ttf
        - asset: assets/fonts/gilroy/Gilroy-BlackItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
        - asset: assets/fonts/gilroy/Gilroy-BoldItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-ExtraBoldItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
        - asset: assets/fonts/gilroy/Gilroy-HeavyItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
        - asset: assets/fonts/gilroy/Gilroy-MediumItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBoldItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Thin.ttf
        - asset: assets/fonts/gilroy/Gilroy-ThinItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-UltraLight.ttf
        - asset: assets/fonts/gilroy/Gilroy-UltraLightItalic.ttf
